### ISSUE TITLE
All sessions have same cookie identifier

### ISSUE THREAD

**Issue by heydenb** [Dynatrace/openkit-dotnet#116]
![UserSessionTags - strange](https://user-images.githubusercontent.com/2580178/73550485-fd846a80-4444-11ea-90a5-fba3797250e7.PNG)

We implemented openkit a while ago and all is working well. The only strange thing we see in Dynatrace is that it's difficult to focus on one user. They are all grouped together apparently based on a cookie according to this screen.

**Comment by stefaneberl** [comment]
Hi Bert,

thanks for your input. The grouping you see here is based on the `deviceID`, which can be set in the appropriate `OpenKitBuilder`.

Hope that explains it a bit.

Best
Stefan

**Comment by stefaneberl** [comment]
Out of curiosity, what is the third value passed to the `DynatraceOpenKitBuilder` constructor?

**Comment by heydenb** [comment]
Meanwhile we found out indeed that it's the deviceId. Since this application is running on Citrix we used the same deviceId everywhere which is not good indeed.
We are looking now to make it something unique per user which makes most sense in a Citrix environment.

Thanks,
Bert

**Comment by stefaneberl** [comment]
If you need help, don't hesitate to contact me.
I'll close this ticket since it can be considered as resolved.

Best
Stefan
