### ISSUE TITLE
Session Properties: Is it possible to add them

### ISSUE THREAD

**Issue by VlaeyenW** [Dynatrace/openkit-dotnet#117]
Hi, 
We are using openkit to monitor user actions inside a WPF application. (Defined as a custom application inside DynaTrace One)
We would like to group users based on their location inside our country (region, office, ...) 
We could use custom IP mapping, but we would rather make use of session properties. 
This would allow use to create meaningful and powerfull user queries

https://www.dynatrace.com/news/blog/filter-user-sessions-based-on-custom-session-properties-eap/
The link above talks about the availability of this as an upcoming improvement for openkit. (aug 2018)
The current implementation of Openkit however does not allow to send custom properties on the session object. (Only on the action object).

Is it possible to add this feature to openkit?
It would help us a lot.

Thx,

**Comment by stefaneberl** [comment]
Hi,

thank you very much for your improvement suggestion. I will discuss it with our product managers.

I got the information from the appropriate developers that it is possible to report session properties also on an Action.

In order to verify it, I have created a simple console application - see the relevant snippet below.
```csharp
            var openKit = new DynatraceOpenKitBuilder(beaconURL, appID, deviceID)
                .Build();

            openKit.WaitForInitCompletion();

            using (var session = openKit.CreateSession())
            {
                session.IdentifyUser("stefan.eberl");

                using (var action = session.EnterAction("Startup"))
                {
                    action.ReportValue("long_value", 42);
                    action.ReportValue("string_value", "The quick brown fox jumps over the lazy dog");
                }
            }

            openKit.Shutdown();
```

After running the console app and waiting for Dynatrace to process the data, I can filter for session properties and I also do see them in the session details.

Nevertheless, I will leave this issue open, until I get a confirmation from PMs.

Best
Stefan

**Comment by heydenb** [comment]
Hey Stefan,

We understand that you are reporting custom values on an action. Which are indeed visible in Dynatrace in the details of the action, but not as session properties like we have in a web application.

Go to: User Sessions -> "Filtered By" box on the top -> String property

**Comment by stefaneberl** [comment]
Hi,

I've been testing the filter in the "User sessions" screen. Attached to this comment you can find a screenshot demonstrating that you can filter for Session Properties.

<img width="960" alt="string_property_sessions" src="https://user-images.githubusercontent.com/32133711/77300117-cf593380-6ced-11ea-85bf-36d4ea158c74.PNG">

I have been informed by PM that this feature is not yet enabled in production. The screenshot is from a development environment.

**Comment by pahofmann** [comment]
Hi Stefan,

is this in production yet? Are there plans to add a "proper way" to add user session attributes directly to the session?

BR
Patrick

**Comment by stefaneberl** [comment]
Hi Patrick,

yes, session properties are already in production.

`Are there plans to add a "proper way" to add user session attributes directly to the session?`
Could you please explain what you consider a "proper way"?

Thanks & BR
Stefan

**Comment by stefaneberl** [comment]
Hi @pahofmann,

any update on this topic?

Best regards,
Stefan

**Comment by pahofmann** [comment]
Hi @stefaneberl,
I switched company and do no longer work with the customer my question was about unfortunately, so it fell of my radar - sorry.

By "proper way" I ment reporting user session properties on the session, like it is in the API of the JS Agent, not an individual action. Or will there be no differentiation between user action and session properties for OpenKit applications?

BR
Patrick

**Comment by stefaneberl** [comment]
Hi @pahofmann,

thanks for the clarification.

OpenKit's API is more related to the OneAgent for iOS/Android API than to the JS Agent.

Please note that neither OpenKit nor OneAgent for iOS/Android are aware of session or action properties, only Dynatrace is.
From Agent/OpenKit perspective an `Action.ReportValue()` API call just sends a key-value pair.
In Dynatrace the user can configure if a reported key-value pair is handled as session property, as action property, or even as both. If the user does not explicitly configure it, it's only shown in Dynatrace as a reported value.

I hope this explains why the API will not change.

BR
Stefan
