### ISSUE TITLE
Install/Update with Nuget

### ISSUE THREAD

**Issue by jamiegs** [Dynatrace/openkit-dotnet#92]
Is there a reason these libraries are not hosted in NuGet?  I'd prefer to use NuGet to make installing and updating the library versions easier.

**Comment by stefaneberl** [comment]
Hi Jamie,
thanks for your question. A version on NuGet will be available within the next two weeks.

**Comment by stefaneberl** [comment]
As of 1.4 OpenKit can be used with NuGet.
The latest 1.4.1 should be used for this (https://www.nuget.org/packages/Dynatrace.OpenKit.NET/)

In addition versions >= 1.4.1 are still deployed to GitHub in a single zip package (e.g. OpenKit.1.4.1.zip
).
