### ISSUE TITLE
The latest versions does not seem to work with AppMon

### ISSUE THREAD

**Issue by heydenb** [Dynatrace/openkit-dotnet#99]
I have a sample with AppMon using the 1.0.1 release which works fine.
But the latest 4.0 release does not work with AppMon. Using fiddler I see a whole bunch of GET requests to /dynatraceMonitor?type=mts

**Comment by stefaneberl** [comment]
Hi,
thank you for your feedback.
Do you mean with the latest 4.0 release OpenKit 1.4.0?

Can you please provide details of your setup (AppMon version)? Response code and the payload from the log?

**Comment by heydenb** [comment]
Hey Stefane.

Yes. it's 4.0 release OpenKit 1.4.0.
I can send you a fiddler session file.

**Comment by thomasgrassauer** [comment]
What version of AppMon are you using? 

It would be great if you could provide us with the log output of a small example app. You can enable verbose logging to the console by calling `EnableVerbose()` when creating the OpenKit instance. Alternatively you can provide a custom logger using the `WithLogger` method.

**Comment by heydenb** [comment]
Version AppMon: 7.2
With EnableVerbose(), no output at all. Even debugged, but it never jumps into errors.

**Comment by stefaneberl** [comment]
Sorry for the delay and thanks for the data.
After some analysis, I think I found a real issue which was introduced when fixing another bug in OpenKit.

I will double check with @thomasgrassauer - just to have another pair of eyes having a look at the solution - and will provide a fix soon.

**Comment by stefaneberl** [comment]
It's fixed already with 1.4.1, 1.3.2, 1.2.2 and 1.1.4.
When using OpenKit .NET 1.4 and above, please consider using the NuGet package ( https://www.nuget.org/packages/Dynatrace.OpenKit.NET/)
